export const MOVE_PIECE = 'MOVE_PIECE';
export const HOLD_PIECE = 'HOLD_PIECE';
export const RELEASE_PIECE = 'RELEASE_PIECE';
export const ENHANCE_MOVABLE_POINT = 'ENHANCE_MOVABLE_POINT';
export const CAPTURE_BLACK_PIECE = 'CAPTURE_BLACK_PIECE';
export const CHANGE_TURN = 'CHANGE_TURN';
export const SHOW_PROMOTE_MODAL = 'SHOW_PROMOTE_MODAL';
export const HIDE_PROMOTE_MODAL = 'HIDE_PROMOTE_MODAL';
